name: Auto-create releases

on:
  schedule:
  - cron: "0 4 * * *"

permissions: 
  contents:write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install

    - name: Update
      run: |
        npm run update
        
    - name: Save work
      run: |
        git add .
        git commit -m "Auto-update ${{ steps.date.outputs.date }}"
        git push

    - name: Publish
      run: |
        npm run publish
      env:
        MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
